### PR TITLE
Strict Mode Fixes

### PR DESCRIPTION
**Pull request by harshithkashyap**
The compiled files both minified and unminified when run in strict mode, various errors are thrown in the console.
Eg: https://plnkr.co/edit/Fbm49w7igo7ea3yjOvvC?p=preview

This PR
- Adds eslint to the project. Uses most of the rules from `jshintrc`
- Changelog.md file
- Exif lib and its methods are available via `cropEXIF` service but the code from `3rdparty/exif.js` is being included in [gulp build stage](https://github.com/CrackerakiUA/ui-cropper/blob/master/gulpfile.js#L107). Excluded `exif.js` from gulp build
- [TODO] Add tests to the repo
There are a couple of more issues mostly from 3rd party libs but i wanted to get the maintainers opinion first before going further. Kindly request review @CrackerakiUA

### CODE REVIEW

**Comment by CrackerakiUA** [comment]
Strange PR, i am not using jshint. Can you check why all checks have failed?

**Comment by rickerd** [comment]
Im okay with a newer linting tool but choose one.
Or jshint, which has clear messages due to jshint stylish.
Or use eslint and completely remove jshint.

And of course.... make Travis pass instead of fail.

**Comment by CrackerakiUA** [comment]
@rickerd pick one, this is on you.

**Comment by rickerd** [comment]
It dont matter to me. H� needs to remove one. It confuses people to have jshint and eslint together.

**Comment by harshithkashyap** [comment]
@CrackerakiUA @rickerd I've disabled eslint for `crop-exif.js` since most of the code is from exif lib. I can fix the lint errors here aswell. What do you guys think?

**Comment by CrackerakiUA** [comment]
@harshithkashyap looks ok, i haven't test yet the result.

**Pull request merged**
