### PR TITLE
added canvasScalemode "fit"

### PR DESCRIPTION
**Pull request by real-artswan**
New option for canvasScalemode to fit image inside ui-cropper container, so if width of the image is bigger than height it uses full width of container and scale height to keep aspect ratio, and otherwise if height is bigger than width.

### CODE REVIEW

**Comment by CrackerakiUA** [comment]
can you provide codepen which provide the new option, so we can test it there?

**Comment by real-artswan** [comment]
Here it is https://codepen.io/real-artswan/pen/ZozOWV

**Comment by CrackerakiUA** [comment]
i had forgotten this, sorry

**Comment by real-artswan** [comment]
Thank you, man!

**Pull request merged**
